@startuml
'https://plantuml.com/class-diagram

abstract class DateCalculator


interface RequestHandler
class HandleRequestActivity extends RequestHandler{
+ requestHandler();

}

class RequestResult extends RequestHandler {
+ getUserBirthdate() : DateFormat MM/DD ;
+ getUserId() : long userId;
+ getUserPronouns(): StringFormat;
}


HandleRequestActivity -|> RequestResult

class UserDao{
+ saveUserInformation();
+ getUserReport(long userId): Elemental, Zodiac;
}


RequestResult -|> ZodiacCalculator

UserDao *-- ZodiacCalculator

UserDao -|> Elemental


abstract class ZodiacCalculator{
    + getZodiacSign(UserInput birthDate) : Zodiac
    + getElementalSign(ZodiacSign zodiac) : Elemental
    + addUserToUserHashMap <HashMap <Elemental, Zodiac> allSignsByElementMap , String> ZodiacUserMap;
}


abstract class GenerateUserId{
    + isValidString() : boolean;
    + generateUserId(): String userId;

}

class Elemental {
+ UserDao userDao;
+ getAllSignsByElement(): HashMap <Elemental, Zodiac> allSignsByElementMap;
+ getUserElementalSign(long userId): Elemental;
+ printUserElementalInformation();

}

class Fire extends Elemental{
+ HashMap <Elemental, Zodiac> fireHashMap;
+ printUserElementalInformation();
}

class Water extends Elemental {
+ HashMap <Elemental, Zodiac> waterHashMap;
+ printUserElementalInformation();

}

class Air extends Elemental{
+ HashMap <Elemental, Zodiac> airHashMap;
+ printUserElementalInformation();
}


class Earth extends Elemental{
+ HashMap <Elemental, Zodiac> earthHashMap;
+ printUserElementalInformation();
}



@enduml